import { useEffect, useMemo, useState } from 'react'
import { extractYouTubeId, getYouTubeThumbnail } from '../../../../lib/youtube'
import { slugify, validateVideoFields } from '../utils'

function Field({ label, error, children }) {
  return (
    <label className="flex flex-col gap-1.5 text-sm font-semibold text-[#333]">
      {label}
      {children}
      {error ? (
        <span className="font-medium text-[#ac222b]" role="alert">
          {error}
        </span>
      ) : null}
    </label>
  )
}

const inputClass =
  'rounded-lg border border-[#ddd] px-3 py-2.5 text-base font-normal text-[#1a1a1a] outline-none focus:border-[#c4782a] focus:ring-2 focus:ring-[#e8a93a]/40'

const textareaClass = `${inputClass} min-h-[120px] resize-y leading-relaxed`

export default function VideoForm({
  initialFields,
  submitting,
  submitLabel,
  onSubmit,
  onCancel,
}) {
  const [fields, setFields] = useState(initialFields)
  const [slugManual, setSlugManual] = useState(Boolean(initialFields.slug))
  const [errors, setErrors] = useState({})

  useEffect(() => {
    setFields(initialFields)
    setSlugManual(Boolean(initialFields.slug))
    setErrors({})
  }, [initialFields])

  const setField = (key, value) => {
    setFields((prev) => {
      const next = { ...prev, [key]: value }
      if (key === 'titleEn' && !slugManual) {
        next.slug = slugify(value)
      }
      return next
    })
  }

  const previewId = useMemo(() => extractYouTubeId(fields.youtubeUrl), [fields.youtubeUrl])
  const previewThumbnail = useMemo(() => getYouTubeThumbnail(previewId), [previewId])

  const handleSubmit = (event) => {
    event.preventDefault()
    const nextErrors = validateVideoFields(fields)
    setErrors(nextErrors)
    if (Object.keys(nextErrors).length > 0) return
    onSubmit(fields)
  }

  return (
    <form
      id="admin-post-form"
      onSubmit={handleSubmit}
      className="mx-auto flex w-full min-w-0 max-w-3xl flex-col gap-5"
    >
      <Field label="YouTube URL" error={errors.youtubeUrl}>
        <input
          className={inputClass}
          placeholder="https://www.youtube.com/watch?v=..."
          value={fields.youtubeUrl}
          onChange={(e) => setField('youtubeUrl', e.target.value)}
        />
      </Field>

      {previewId ? (
        <div className="w-full max-w-md">
          <span className="text-sm font-semibold text-[#333]">Preview</span>
          <div className="relative mt-1.5 aspect-video w-full overflow-hidden rounded-lg border border-[#ddd] bg-[#f3f0eb]">
            <img
              src={previewThumbnail}
              alt="Video thumbnail preview"
              className="absolute inset-0 size-full object-cover"
            />
          </div>
          <p className="mt-1 text-xs text-[#888]">
            The final thumbnail and embed are generated by the server from this URL.
          </p>
        </div>
      ) : null}

      <div className="grid gap-4 sm:grid-cols-2">
        <Field label="Title (English)" error={errors.titleEn}>
          <input
            className={inputClass}
            value={fields.titleEn}
            onChange={(e) => setField('titleEn', e.target.value)}
          />
        </Field>
        <Field label="Title (Kannada)" error={errors.titleKn}>
          <input
            className={inputClass}
            value={fields.titleKn}
            onChange={(e) => setField('titleKn', e.target.value)}
          />
        </Field>
      </div>

      <Field label="Slug" error={errors.slug}>
        <input
          className={inputClass}
          value={fields.slug}
          onChange={(e) => {
            setSlugManual(true)
            setField('slug', e.target.value)
          }}
          placeholder="auto-generated from English title"
        />
      </Field>

      <div className="grid gap-4 sm:grid-cols-2">
        <Field label="Category (English) — optional">
          <input
            className={inputClass}
            value={fields.categoryEn}
            onChange={(e) => setField('categoryEn', e.target.value)}
          />
        </Field>
        <Field label="Category (Kannada) — optional">
          <input
            className={inputClass}
            value={fields.categoryKn}
            onChange={(e) => setField('categoryKn', e.target.value)}
          />
        </Field>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <Field label="Description (English) — optional">
          <textarea
            className={textareaClass}
            value={fields.bodyEn}
            onChange={(e) => setField('bodyEn', e.target.value)}
          />
        </Field>
        <Field label="Description (Kannada) — optional">
          <textarea
            className={textareaClass}
            value={fields.bodyKn}
            onChange={(e) => setField('bodyKn', e.target.value)}
          />
        </Field>
      </div>

      <div className="flex flex-wrap gap-3 pt-2">
        <button
          type="submit"
          disabled={submitting}
          className="rounded-lg bg-[#ac222b] px-5 py-2.5 text-sm font-bold text-white hover:bg-[#8f1c24] disabled:opacity-70"
        >
          {submitting ? 'Saving…' : submitLabel}
        </button>
        {onCancel ? (
          <button
            type="button"
            onClick={onCancel}
            className="rounded-lg border border-[#ddd] bg-white px-5 py-2.5 text-sm font-semibold text-[#333] hover:bg-[#f6f1ea]"
          >
            Cancel
          </button>
        ) : null}
      </div>
    </form>
  )
}
